accounts/urls.py
# from django.urls import path
# from . import views
# from django.shortcuts import render, redirect
from django.contrib.auth.models import User
# from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
# from django.views.generic import TemplateView
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/',
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),
    path('logout/',
        auth_views.LogoutView.as_view(),
        name='logout'),
    path('signup/',
            views.sign_up,
            name='signup'),
    path('profile/',
            views.user_profile,
            name='profile'),
    path('edit/',
            views.edit_profile,
            name='editprofile'),
    path('change_password/',
            views.change_password,
            name='change_password'),
    # path('reset_pass/', auth_views.password_reset, name = 'password_reset'),
    # path('reset_pass_done/', auth_views.password_reset_done, name = 'password_reset_done'),
    # path('reset_pass_confirm/', auth_views.password_reset_confirm, name = 'password_reset_confirm')

    path('password_reset/',
            auth_views.PasswordResetView.as_view(), name = 'password_reset'),
    path('password_reset_done/',
            auth_views.PasswordResetDoneView.as_view(), name = 'password_reset_done'),
    path('password_reset_confirm/(?P<uid64>[0-9A-Za-z]+)-(?P<token>.+)/',
            auth_views.PasswordResetConfirmView.as_view(), name = 'password_reset_confirm'),
    path('passchangedone/',auth_views.PasswordChangeDoneView.as_view(), name = 'password_reset_complete' )
    # path('password_reset_confirm/(?P<uid64>[0-9A-Za-z]+)-(?P<token>.+)/',
    #         auth_views.PasswordResetConfirmView.as_view(), name = 'password_reset_confirm')
    # # path(
    #     'changepass/',
    #     auth_views.PasswordChangeView.as_view(template_name='accounts/changepass.html'),
    # ),

    # path("signup/", views.signup, name='signup'),#register
]

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('groupa/', views.groupa, name='groupa'),
    path("groupb/", views.groupb, name='groupb'),
    path("groupc/", views.groupc, name='groupc'),
    path("groupd/", views.groupd, name='groupd'),
]

net/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from net import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('accounts/', include("accounts.urls")),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('groups/', include("groups.urls")),
    path('accounts/', include('django.contrib.auth.urls')),

]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
      <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes">
              <title>Vrtic!</title>
              <!-- Latest compiled and minified CSS -->
              <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
              <!-- <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> -->
      </head>
{% if user.is_authenticated %}
<body>

    <div class="pos-f-t">
      <div class="collapse fixed-bottom" id="navbarVrtic">
        <div class="bg-dark p-0">
          <div class="container-fluid">


          <ul class=" nav navbar-nav navbar-dark bg-dark fixed-top">
            <li><a href="{% url 'home' %}"  class="btn btn-simple ">Home</a></li>
            <li><a href="{% url 'accounts:editprofile' %}"  class="btn btn-simple ">Editovanje</a></li>
            <li><a href="#"  class="btn btn-simple ">dugovanja</a></li>
            <li><a href="{% url 'accounts:profile' %}"  class="btn btn-simple ">info</a></li>

            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Izloguj me</a></li>
            </ul>
          </ul>
          </div>


          <span class="text-muted"></span>
        </div>
      </div>
          <nav class="navbar navbar-dark bg-transparent fixed-bottom">
            <div class="container">
            <button class="navbar-toggler justify-content-center bg-dark" type="button" data-toggle="collapse" data-target="#navbarVrtic" aria-controls="navbarVrtic" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>


          </nav>
  </div>



        {% block content %}
        {% endblock %}
        <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>
</body>


{% else %}
<meta charset="utf-8">


<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
        <h2 class="text-center">Dobrodošli</h2>
        <a href="{% url 'accounts:login' %}"><img src="{% static "/media/logo.png" %}" alt="My image" class="center-block img-responsive" > </a>
        <h2 class="text-center">Kliknite na ikonicu!</h2>

    </div>





  </div>
</div>
 {% endif %}



  </html>

templates/grupa1.html
{% extends "base.html" %}
{% block content %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


  </head>
  <body>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Ime</th>
          <th scope="col">Vaspitac</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Luka</td>
      <td>Marija</td>
    </tr>
    <tr>
      <th scope="row">2</th>

      <td>Natko</td>
      <td>Marija</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Djurdja</td>
      <td>Marija</td>
    </tr>


  </tbody>
</table>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
  {% endblock %}

templates/grupa2.html
{% extends "base.html" %}
{% block content %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


  </head>
  <body>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Ime</th>
      <th scope="col">Prezime</th>
      <th scope="col">Vaspitac</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td><a href="">@Luka</a></td>
      <td>@Pavlovic</td>
      <td>@Marija</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td><a href="">Marko</a></td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>


  </tbody>
</table>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
  {% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Vrtic novo</title>
  </head>
  <body>
    <div class="container">
  <div class="row">
    <div class="col-md-3">

        <a href="{% url 'groups:groupa' %}"><img src="{% static "/media/buba.jpg" %}" alt="My image" class="img-circle img-responsive" > </a>


    </div>





    <div class="col-xs-1 col-md-3">

          <a href="{% url 'groups:groupb' %}"><img src="{% static "/media/patka.jpg" %}" alt="My image" class="img-circle img-responsive" > </a>



    </div>

    <div class="col-xs-1 col-md-3">

          <a href="{% url 'groups:groupa' %}"><img src="{% static "/media/pcela.jpg" %}" alt="My image" class="img-circle img-responsive" > </a>

    </div>



    <div class="col-xs-1 col-md-3">

          <a href="{% url 'groups:groupa' %}"><img src="{% static "/media/leptir.jpg" %}" alt="My image" class="img-circle img-responsive" > </a>

    </div>
    <div class="col-xs-1 col-md-3">

          <a href="{% url 'groups:groupa' %}"><img src="{% static "/media/leptir.jpg" %}" alt="My image" class="img-circle img-responsive" > </a>

    </div>


    </div>






    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    </body>
</html>
  {% endblock %}

templates/thanks.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes">
        <title>Hvala na poseti!</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
</head>
  <body>
    <div class="container jumbotron text-center">
      <h1>Hvala na poseti, vratite nam se uskoro!</h1>
      </div>
    <div class="container   btn-group-vertical">

      <a class="btn btn-primary btn-lg btn-danger" href="https://www.facebook.com/Pred%C5%A1kolska-ustanova-Beli-Dvorac-149067775495339/" role="button">Facebook</a>
      <a class="btn btn-primary btn-lg btn-danger" href="http://belidvorac.rs/" role="button">Web stranica</a>
      <a class="btn btn-primary btn-lg btn-danger" href="{% url 'accounts:login' %}" role="button">Ulogujte se</a>


    </div>
  </body>
</html>